require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Product = require('../models/Product');
const User = require('../models/User');

const img = (seed, w = 600, h = 600) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

const products = [
  {
    title: 'Apple iPhone 15 Pro',
    description: 'The most advanced iPhone ever with titanium design, A17 Pro chip, and a customizable Action Button. Shoot breathtaking photos with the pro camera system.',
    price: 134900,
    discountedPrice: 124900,
    category: 'Electronics',
    brand: 'Apple',
    stock: 50,
    images: [img('iphone15', 600, 600), img('iphone15b', 600, 600)],
    rating: 4.8,
    numReviews: 2341,
    featured: true,
    tags: ['smartphone', 'apple', '5g', 'ios'],
  },
  {
    title: 'Samsung Galaxy S24 Ultra',
    description: 'Galaxy AI is here. Samsung Galaxy S24 Ultra with built-in S Pen, 200MP camera, and Snapdragon 8 Gen 3 for Galaxy.',
    price: 129999,
    discountedPrice: 119999,
    category: 'Electronics',
    brand: 'Samsung',
    stock: 40,
    images: [img('samsung24', 600, 600), img('samsung24b', 600, 600)],
    rating: 4.7,
    numReviews: 1876,
    featured: true,
    tags: ['smartphone', 'samsung', '5g', 'android'],
  },
  {
    title: 'Sony WH-1000XM5 Headphones',
    description: 'Industry-leading noise canceling with two processors and eight microphones. Crystal clear calls with 4 beamforming microphones. Up to 30-hour battery life.',
    price: 29990,
    discountedPrice: 24990,
    category: 'Electronics',
    brand: 'Sony',
    stock: 80,
    images: [img('sonyheadphones', 600, 600), img('sonyheadphonesb', 600, 600)],
    rating: 4.9,
    numReviews: 5432,
    featured: true,
    tags: ['headphones', 'noise-canceling', 'wireless'],
  },
  {
    title: 'MacBook Air M2',
    description: 'Supercharged by M2. Up to 18 hours battery life, stunning 13.6-inch Liquid Retina display, MagSafe charging, and the best laptop keyboard.',
    price: 114900,
    discountedPrice: null,
    category: 'Electronics',
    brand: 'Apple',
    stock: 30,
    images: [img('macbookair', 600, 600)],
    rating: 4.9,
    numReviews: 3210,
    featured: true,
    tags: ['laptop', 'apple', 'macbook', 'm2'],
  },
  {
    title: 'boAt Airdopes 141',
    description: 'boAt Airdopes 141 True Wireless Earbuds with 42H Playback, ENx Tech, BEAST Mode, IWS, IPX4 Water Resistance and Smooth Touch Controls.',
    price: 1999,
    discountedPrice: 999,
    category: 'Electronics',
    brand: 'boAt',
    stock: 200,
    images: [img('earbuds', 600, 600)],
    rating: 4.1,
    numReviews: 87432,
    featured: false,
    tags: ['earbuds', 'wireless', 'boat'],
  },
  {
    title: 'Samsung 55" 4K QLED TV',
    description: 'QLED 4K Smart TV with Quantum Dot technology, Alexa built-in, Motion Xcelerator Turbo+ for 120Hz gaming, and ultra-slim design.',
    price: 89990,
    discountedPrice: 74990,
    category: 'Electronics',
    brand: 'Samsung',
    stock: 20,
    images: [img('samsungtv', 600, 600)],
    rating: 4.6,
    numReviews: 1243,
    featured: false,
    tags: ['tv', 'qled', '4k', 'samsung'],
  },
  {
    title: 'Nike Air Max 270',
    description: 'The Nike Air Max 270 delivers a comfortable ride with the tallest Air unit yet. The mesh upper keeps you cool while the foam midsole cushions every step.',
    price: 12995,
    discountedPrice: 9995,
    category: 'Clothing',
    brand: 'Nike',
    stock: 120,
    images: [img('nikeairmax', 600, 600)],
    rating: 4.5,
    numReviews: 3420,
    featured: true,
    tags: ['shoes', 'nike', 'running', 'sneakers'],
  },
  {
    title: "Levi's 511 Slim Fit Jeans",
    description: "Levi's 511 Slim Fit Jeans are cut close to the body from hip to ankle. Made from stretch denim that moves with you all day.",
    price: 3999,
    discountedPrice: 2999,
    category: 'Clothing',
    brand: "Levi's",
    stock: 150,
    images: [img('levisjeans', 600, 600)],
    rating: 4.4,
    numReviews: 5678,
    featured: false,
    tags: ['jeans', 'denim', 'levis', 'men'],
  },
  {
    title: "Men's Casual Hoodie",
    description: 'Premium fleece hoodie with kangaroo pocket and adjustable drawstring hood. Perfect for everyday wear. Available in multiple colors.',
    price: 1999,
    discountedPrice: 1499,
    category: 'Clothing',
    brand: 'H&M',
    stock: 200,
    images: [img('hoodie', 600, 600)],
    rating: 4.2,
    numReviews: 2341,
    featured: false,
    tags: ['hoodie', 'casual', 'men', 'winter'],
  },
  {
    title: "Women's Floral Midi Dress",
    description: 'Elegant floral print midi dress with a flattering A-line silhouette. Made from lightweight fabric, perfect for summer outings and parties.',
    price: 2499,
    discountedPrice: 1799,
    category: 'Clothing',
    brand: 'Zara',
    stock: 90,
    images: [img('floraldress', 600, 600)],
    rating: 4.6,
    numReviews: 1876,
    featured: true,
    tags: ['dress', 'women', 'floral', 'summer'],
  },
  {
    title: 'Atomic Habits',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear, one of the world\'s leading experts on habit formation, reveals practical strategies.',
    price: 799,
    discountedPrice: 549,
    category: 'Books',
    brand: 'Penguin Random House',
    stock: 500,
    images: [img('atomichabits', 600, 600)],
    rating: 4.9,
    numReviews: 45321,
    featured: true,
    tags: ['self-help', 'habits', 'productivity', 'bestseller'],
  },
  {
    title: 'The Psychology of Money',
    description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money isn\'t necessarily about what you know. It\'s about how you behave.',
    price: 599,
    discountedPrice: 399,
    category: 'Books',
    brand: 'Jaico Publishing',
    stock: 400,
    images: [img('psychmoney', 600, 600)],
    rating: 4.8,
    numReviews: 32109,
    featured: false,
    tags: ['finance', 'self-help', 'money', 'bestseller'],
  },
  {
    title: 'Clean Code',
    description: 'A handbook of agile software craftsmanship by Robert C. Martin. Even bad code can function, but if code isn\'t clean, it can bring a development organization to its knees.',
    price: 3999,
    discountedPrice: 2999,
    category: 'Books',
    brand: 'Pearson',
    stock: 150,
    images: [img('cleancode', 600, 600)],
    rating: 4.7,
    numReviews: 12456,
    featured: false,
    tags: ['programming', 'software', 'coding', 'tech'],
  },
  {
    title: 'Instant Pot Duo 7-in-1',
    description: 'The #1 selling multi-cooker. Pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker and warmer all in one appliance.',
    price: 8999,
    discountedPrice: 6499,
    category: 'Home & Kitchen',
    brand: 'Instant Pot',
    stock: 60,
    images: [img('instantpot', 600, 600)],
    rating: 4.7,
    numReviews: 23456,
    featured: true,
    tags: ['kitchen', 'pressure-cooker', 'appliance'],
  },
  {
    title: 'Philips Air Fryer',
    description: 'Fry, bake, grill, roast and reheat with up to 90% less fat. The Philips Air Fryer uses Rapid Air technology for crispy results using little to no oil.',
    price: 12999,
    discountedPrice: 9999,
    category: 'Home & Kitchen',
    brand: 'Philips',
    stock: 45,
    images: [img('airfryer', 600, 600)],
    rating: 4.5,
    numReviews: 15678,
    featured: false,
    tags: ['kitchen', 'airfryer', 'healthy', 'cooking'],
  },
  {
    title: 'Yoga Mat Premium',
    description: 'Non-slip yoga mat with alignment lines, extra thick 6mm cushioning, eco-friendly TPE material. Perfect for yoga, pilates and exercise.',
    price: 1499,
    discountedPrice: 999,
    category: 'Sports',
    brand: 'Boldfit',
    stock: 300,
    images: [img('yogamat', 600, 600)],
    rating: 4.3,
    numReviews: 8765,
    featured: false,
    tags: ['yoga', 'fitness', 'exercise', 'mat'],
  },
  {
    title: 'Adjustable Dumbbell Set',
    description: 'Adjustable dumbbell set with quick-change weight selector. Replaces 15 sets of weights. Ideal for home gyms. Range: 2.5kg to 24kg per dumbbell.',
    price: 15999,
    discountedPrice: 12499,
    category: 'Sports',
    brand: 'PowerBlock',
    stock: 35,
    images: [img('dumbbells', 600, 600)],
    rating: 4.6,
    numReviews: 3214,
    featured: true,
    tags: ['gym', 'weights', 'fitness', 'workout'],
  },
  {
    title: 'Lakme Face Serum',
    description: 'Lakme 9 to 5 Vitamin C+ Face Serum with Niacinamide for glowing skin. Brightens, reduces dark spots, and improves skin texture with daily use.',
    price: 599,
    discountedPrice: 449,
    category: 'Beauty',
    brand: 'Lakme',
    stock: 400,
    images: [img('faceserum', 600, 600)],
    rating: 4.2,
    numReviews: 19876,
    featured: false,
    tags: ['skincare', 'serum', 'vitamin-c', 'beauty'],
  },
  {
    title: "L'Oréal Revitalift Moisturizer",
    description: "L'Oréal Paris Revitalift 1.5% Pure Hyaluronic Acid Face Moisturizer. Plumps skin and reduces wrinkles in 4 weeks. Suitable for all skin types.",
    price: 1199,
    discountedPrice: 899,
    category: 'Beauty',
    brand: "L'Oréal",
    stock: 200,
    images: [img('moisturizer', 600, 600)],
    rating: 4.5,
    numReviews: 12345,
    featured: false,
    tags: ['skincare', 'moisturizer', 'loreal', 'beauty'],
  },
  {
    title: 'Mi Smart Watch',
    description: 'Xiaomi Smart Watch with 1.43" AMOLED display, 117 workout modes, 5ATM water resistance, and up to 12-day battery life. Health tracking with SpO2 and heart rate.',
    price: 4999,
    discountedPrice: 3499,
    category: 'Electronics',
    brand: 'Xiaomi',
    stock: 100,
    images: [img('smartwatch', 600, 600)],
    rating: 4.3,
    numReviews: 7654,
    featured: false,
    tags: ['smartwatch', 'fitness', 'xiaomi', 'wearable'],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('🗑️  Cleared existing products');

    // Insert products
    const inserted = await Product.insertMany(products);
    console.log(`✅ Inserted ${inserted.length} products`);

    // Seed default admin user
    const existingAdmin = await User.findOne({ email: 'admin@shop.com' });
    if (!existingAdmin) {
      await User.create({
        name: 'Admin User',
        email: 'admin@shop.com',
        password: 'admin123',
        role: 'admin',
      });
      console.log('✅ Admin user created: admin@shop.com / admin123');
    } else {
      console.log('ℹ️  Admin user already exists');
    }

    console.log('\n🎉 Seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error.message);
    process.exit(1);
  }
};

seedDB();
